# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shain',
            fields=[
                ('shain_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('status', models.CharField(blank=True, choices=[('0', '退勤'), ('1', '出勤')], max_length=2, verbose_name='status')),
            ],
        ),
    ]
