# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_workhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='update_date',
            field=models.DateTimeField(verbose_name='update_date'),
        ),
    ]
